name: Chromium Dr. Memory WebGL Test

on: [push, pull_request]

jobs:
  test-chromium-dr-memory:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dr. Memory
        run: |
          curl -LO https://github.com/DynamoRIO/dynamorio/releases/download/cronbuild-10.93.19944/DynamoRIO-Windows-10.93.19944.zip
          tar -xvzf DynamoRIO-Windows-10.93.19944.zip

      - name: Install Chromium dependencies
        run: |
          # Add commands to install Chromium dependencies (node, python, depot_tools, etc.)
          # Install WebGL support if needed
          
      - name: Build and Run Chromium with WebGL and DrMemory
        run: |
          DynamoRIO-Windows-10.93.19944/bin64/drrun.exe -- build/Release/chrome.exe --args --load-extension=webgl
          
